# Autogenerated by Astropy-affiliated package astropy_helpers's setup.py on 2015-07-22 15:34:48.531461
from __future__ import unicode_literals
import datetime

version = "1.0.3"
githash = "90de2d8340d1eafaface009625056ca62f5a6c76"


major = 1
minor = 0
bugfix = 3

release = True
timestamp = datetime.datetime(2015, 7, 22, 15, 34, 48, 531461)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
