# Autogenerated by Astropy's setup.py on 2015-08-11 11:39:24.431716
from __future__ import unicode_literals
import datetime

version = "1.0.4"
githash = "9fb669b12116b1624737406757ac5daca7fbae02"


major = 1
minor = 0
bugfix = 4

release = True
timestamp = datetime.datetime(2015, 8, 11, 11, 39, 24, 431716)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
