# Autogenerated by Astropy-affiliated package astropy_helpers's setup.py on 2015-04-16 11:25:55.599810
from __future__ import unicode_literals
import datetime

version = "1.0.2"
githash = "161773fa72d916c498e0a2a513ecc24460244ac8"


major = 1
minor = 0
bugfix = 2

release = True
timestamp = datetime.datetime(2015, 4, 16, 11, 25, 55, 599810)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
