# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "3.5.5"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\continuous-integration\\appveyor\\windows_sdk.cmd"
      PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                        # of 32 bit and 64 bit builds are needed, move this
                        # to the matrix section.

  matrix:
      - PYTHON_VERSION: "2.6"
      - PYTHON_VERSION: "2.7"
      - PYTHON_VERSION: "3.4"

platform:
    -x64

install:
    # Install miniconda using a powershell script.
    - "powershell continuous-integration/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

    # Install the build and runtime dependencies of the project.
    - "conda update --yes conda"

    # Create a conda environment
    - "conda create -q --yes -n test python=%PYTHON_VERSION%"
    - "activate test"

    # Check that we have the expected version of Python
    - "python --version"

    # Install specified version of numpy and dependencies
    - "conda install -q --yes numpy Cython sphinx pytest"

    # Some of the tests use git commands that require a user to be configured
    - git config --global user.name "A U Thor"
    - git config --global user.email "author@example.com"

    # Install graphviz
    - cinst graphviz.portable

# Not a .NET project, we build SunPy in the install step instead
build: false

test_script:
  - "%CMD_IN_ENV% py.test"

